---
general-en: &default
  title: General Roman Calendar
  language: en
  files:
    - universal-en.txt

general-la:
  title: Calendarium Romanum Generale
  language: la
  files:
    - universal-la.txt

czech:
  title: Český národní kalendář
  language: cs
  files:
    - czech-cs.txt

default:
  <<: *default